language: python
sudo: required
before_script:
  - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx -C /tmp
script:
  - cd ./tests
  - ./runtests
notifications:
  email:
    on_success: never

